<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Fuookami.Ospf.Core.Plugin.Lingo</RootNamespace>
    <AssemblyName>Fuookami.Ospf.Core.Plugin.Lingo</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Fuookami.Ospf.Core.Plugin.Lingo.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Utils\Utils.csproj" />
    <ProjectReference Include="..\Math\Math.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Framework\Framework.csproj" />
  </ItemGroup>
</Project>
