<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Fuookami.Ospf.Quantities</RootNamespace>
    <AssemblyName>Fuookami.Ospf.Quantities</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Fuookami.Ospf.Quantities.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Utils\Utils.csproj" />
    <ProjectReference Include="..\Math\Math.csproj" />
  </ItemGroup>
</Project>
